name: buildah-build-push
description: Build and push container image with Buildah and Podman

inputs:
  username:
    default: ''
    required: true
  password:
    default: ''
    required: true
  registry:
    default: ''
    required: true
  image:
    default: ''
    required: true
  tags:
    default: latest
    required: false
  platforms:
    default: linux/amd64, linux/arm64
    required: false
  context:
    default: .
    required: false
  containerfiles:
    default: ./Containerfile
    required: false
  build-args:
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Install QEMU dependency
      shell: bash
      run: |
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends \
        qemu-user-static

    - uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.image }}
        tags: ${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}
        context: ${{ inputs.context }}
        containerfiles: ${{ inputs.containerfiles }}
        build-args: ${{ inputs.build-args }}

    - uses: redhat-actions/push-to-registry@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        registry: ${{ inputs.registry }}
        image: ${{ inputs.image }}
        tags: ${{ inputs.tags }}
